### PR TITLE
Reconnect buffer + MAC address support + fixes

### PR DESCRIPTION
**Pull request by cathery**
Ok so this is a lot to dig in, i found plenty of various issues while testing the app since the last commit.  I'm gonna list my main revelations and steps i took to change them.

- The app would sometimes disconnect due to shoddy wifi connection and on immediate reconnection it would start the elapsed time from the beginning. Instead of resetting the time every time the client makes a connection, i made a timer in the same thread that goes off after 15 seconds to reset the elapsed time. That way, i gave the app some leeway to reconnect without losing the elapsed timer.
- Sometimes I'd notice that the app would keep showing that it's connected despite the switch being obviously offline. This has been already fixed by throwing an exception if the received bytes are 0, i approached that problem by adding a check in case the byte magic does not add up (there was none before). I believe that's a better solution long-term.
- I added the option to find the switch by IP as well as MAC address. Since IP addresses are assigned dynamically, this solves the issue of having to re-enter the switch IP every time the IP addresses are reassigned (ex. restarting the router in your local network). Additionally, i added a button that lets you convert your IP address to a MAC address so you don't have to go looking for it in your network.
- The "tray icon duplication" bug was a fluke. The main form would dispose of the tray icon regardless, so disposing of the tray icon on form closing was pointless. The real reason i get the tray duplication is due to me stopping the app via the visual studio debug menu. This stops the process entirely and there is sadly no way to check for that internally.
- I fixed the issue where the tray icon did not update when the connection was lost.

### CODE REVIEW

**Comment by SunTheCourier** [comment]
Thanks for another PR! I will do some of my own testing when I can!

**Comment by SunTheCourier** [comment]
Could you dispose of the timer you introduced?

**Comment by cathery** [comment]
Why?

**Comment by SunTheCourier** [comment]
Just after you done using it in the code I mean ^^

**Comment by cathery** [comment]
Ohhhhh my bad

**Comment by SunTheCourier** [comment]
overall this PR looks good only complaint i could bring up is MAC address lookup takes longer than an IP

**Comment by cathery** [comment]
That should be expected, since the program needs to look up the IP address from the ARP compared to directly using the IP

**Comment by cathery** [comment]
thank you 🙏

**Pull request merged**
