### PR TITLE
GUI Client: Add an option to display Main Menu as status

### PR DESCRIPTION
**Pull request by cathery**
This is the compromise from my PRs in the past. I wish there was an option to not display main menu status on rich presence, because i'm often idle and it bugs the frick out of me.

### CODE REVIEW

**Comment by iomintz** [comment]
:+1: I would like this feature as well, but I'd like it in the CLI client. I wonder if it would be better to put this in the Server instead. If so configured, avoid sending updates for the main menu title at all. That way it would not need to be supported in both the GUI and the CLI client.

**Comment by cathery** [comment]
I would add this to the CLI client as well, but I didn't see how to pass any options besides the initial IP and ID, so I didn't do anything without further instruction.

**Comment by SunTheCourier** [comment]
I was thinking about adding https://github.com/commandlineparser/commandline to help with options but im still not sure if thats the best approach for options

**Comment by iomintz** [comment]
Argument parsing works. For a long-running process, it's more common to have a separate configuration file. Something like `client --config /path/to/config` would do nicely. Something more human-friendly than JSON (no comments, bothersome quoting rules for non-developers), such as INI or TOML would be preferred.

**Pull request merged**
